---
groups:
- name: main
  jobs:
  - install
  - test
  - deploy-job
resources:
- name: crud
  type: git
  source:
    uri: https://github.com/vc4017/crud-operations-on-mongodb.git
    branch: master

- name: cf-env
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tovenki.ch@gmail.com
    password: Venki@521
    organization: concourse-node.js app
    space: deployment
    skip_cert_check: true

jobs:

- name: install
  serial: true
  disable_manual_trigger: false
  plan:
      - get: crud
        trigger: true

      - task: npm-install
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "6" }
          inputs:
            - name: crud
              path: .
          run:
            path: npm
            args: [ install ]
            
- name: test
  serial: true
  disable_manual_trigger: false
  plan:
      - get: crud
        trigger: true
        
      - task: npm-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "6" }
          inputs:
            - name: crud
              path: .
          run:
            path: npm
            args: [ install-test ]

- name: deploy-job
  serial: true
  plan:
  - {get: basic-express-site-2016, trigger: true}
  - put: cf-env
    params:
      manifest: basic-express-site-2016/manifest.yml
      path: basic-express-site-2016
